version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: divyamoilla/divya
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t divyamoilla/divya:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar divyamoilla/divya
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
    working_directory: /tmp/workspace
steps:
      - run:
          name: Creating Artifacts
          command: |
            echo "divya@2662" | docker login -u "divyamoilla" --password-stdin
            cp image.tar > /tmp/artifact-1;
      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file
