version: 2
jobs:
  upload-artifact:
    docker:
      - image: circleci/openjdk:8-jdk
        auth:
          username: divyamoilla
          password: divya@2662  # context / project UI env-var reference
    working_directory: /tmp
    steps:
      - checkout
      - run: mvn dependency:go-offline
      - run:
          name: maven build
          command: |
            mvn clean install
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
