version: 2
jobs:
  build:
    docker:
      - image: python:3.6.3-jessie
        auth:
          username: divyamoilla
          password: divya@2662  # context / project UI env-var reference

    working_directory: /tmp
    steps:
      - run:
          name: Creating Artifacts
          command: |
		    mkdir /tmp/artifacts;
            cp Frontend/ /tmp/artifact/image;
      - store_artifacts:
          path: /tmp/artifact/image
